# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_df = pd.read_csv("../WeatherPy/output_data/cities.csv")
cities_df

,City,Country,Date,Temperature,Latitude,Longitude,Humidity,Cloudiness,Wind Speed
0,puerto ayora,EC,1627339976,76.96,-0.7393,-90.3518,83,46,7.00
1,deming,US,1627339976,91.29,32.2687,-107.7586,22,1,8.05
2,castro,BR,1627339976,58.44,-24.7911,-50.0119,65,4,4.41
3,xingcheng,CN,1627339977,77.38,40.6167,120.7167,87,96,3.36
4,kavieng,PG,1627339977,83.66,-2.5744,150.7967,69,42,7.54
...,...,...,...,...,...,...,...,...,...
554,danville,US,1627339882,88.23,36.5860,-79.3950,75,90,4.61
555,mersing,MY,1627340116,76.91,2.4312,103.8405,94,44,5.75
556,san quintin,MX,1627340117,72.55,30.4833,-115.9500,71,18,10.27
557,zacualpan,MX,1627340117,86.72,21.2500,-105.1667,79,92,6.15
558,socorro,US,1627339959,95.02,31.6546,-106.3033,34,92,3.11

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
#cONFIGURE GMAPS
gmaps.configure(api_key = g_key)

In [12]:
# Store latitude and longitude in locations
locations = cities_df[["Latitude", "Longitude"]]

# Create weight with humidity
humidity = cities_df["Humidity"].astype(float)

In [15]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
heat_layer

WeightedHeatmap(data_bounds=[(-44.49757629827559, -179.99999), (85.0, 179.99999)], dissipating=False, locationâ€¦

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.
* A max temperature lower than 80 degrees but higher than 70.
* Wind speed less than 10 mph.
* Zero cloudiness.

In [17]:
weather_df = cities_df[(cities_df["Temperature"] >= 70)&
                       (cities_df["Temperature"] <= 80)&
                       (cities_df["Wind Speed"] <= 10)&
                       (cities_df["Cloudiness"] == 0)].dropna()
weather_df

,City,Country,Date,Temperature,Latitude,Longitude,Humidity,Cloudiness,Wind Speed
24,port elizabeth,ZA,1627339828,70.11,-33.9180,25.5701,29,0,8.05
31,mauguio,FR,1627339983,78.69,43.6181,4.0074,36,0,8.05
46,kosonsoy,UZ,1627339986,77.56,41.2561,71.5508,25,0,6.22
63,syracuse,IT,1627339991,78.44,37.0881,15.2792,62,0,7.54
97,bayeux,BR,1627339999,77.63,-7.1250,-34.9322,83,0,6.91
232,alexandria,EG,1627339871,76.96,31.2156,29.9553,78,0,5.75
294,lixourion,GR,1627340048,77.65,38.2019,20.4314,61,0,4.88
314,fukue,JP,1627340052,79.38,32.6881,128.8419,78,0,1.16
333,tatawin,TN,1627340058,78.46,32.9297,10.4518,52,0,2.93
434,leonforte,IT,1627340084,77.83,37.6443,14.4007,39,0,1.72
529,rosetta,EG,1627340053,76.82,31.4044,30.4164,70,0,5.30

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
hotel_df = weather_df
hotel_df["Hotel Name"] = ""

In [ ]:
# geocoordinates
for coordinate in 
target_coordinates = "43.6187102, -116.2146068" 
target_search = "Chinese"
target_radius = 8000
target_type = "restaurant"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": gkey
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

In [ ]:
# convert response to json
places_data = response.json()

# Print the json (pretty printed)
print(json.dumps(places_data, indent=4, sort_keys=True))

In [ ]:
# Print the name and address of the first restaurant that appears
print(places_data["results"][0]["name"])
print(places_data["results"][0]["vicinity"])

In [ ]:
# Convert poverty rate as a list
# Convert bank rate to list
poverty_rate = census_data["Poverty Rate"].tolist()

In [ ]:
# Create a map using state centroid coordinates to set markers
marker_locations = census_data[['Latitude', 'Longitude']]

# Create a marker_layer using the poverty list to fill the info box
fig = gmaps.figure()
markers = gmaps.marker_layer(marker_locations,
    info_box_content=[f"Poverty Rate: {rate}" for rate in poverty_rate])
fig.add_layer(markers)
fig

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure